TESTS/Makefile.am, TESTS/test-dnsimp.sh
=> execute the dnsimp test in the right directory

TESTS/bug_1315_double.c, TESTS/bug_1315_single.c
Doesn't matter that much since it's in a test, but might as well not leak memory on purpose.
=> add missing free

.travis.yml
Close #25. Not sure why it's failing on travis. Openblas is working fine with a 32 bits and 64 bits machine here.
=> try to use reference blas

CHANGES, SRC/dnapps.f, SRC/dsapps.f
I came across this patch online, although the issue doesn't personally affect me, it said "We have contacted the ARPACK developers and made them aware of this issue", so it seemed worth suggesting it here.
https://software.intel.com/en-us/articles/how-to-resolve-arpack-issues-with-intel-mkl-110-update-3
=> fix usages of DLACPY to not alias inputs

CHANGES, configure.ac
Tested on latest Cygwin 32 and 64bit. No test failure.
No idea why "AC_FC_LINE_LENGTH(unlimited)" was introduced but I guess mixing F77 with FC  commands is confusing Autoconf at least on Cygwin in this case
$ gfortran --version
GNU Fortran (GCC) 5.4.0
=> removing AC_FC_LINE_LENGTH to solve #41 on Cygwin

CMakeLists.txt, arpack-ng-config.cmake.in
CMake: find_package for both parpack and arpack (for now, works only for arpack).
/tmp> cp /path/to/arpack-ng/PARPACK/EXAMPLES/MPI/*.f .
/tmp> cp /path/to/arpack-ng/PARPACK/EXAMPLES/MPI/*.h .
/tmp> more CMakeLists.txt
cmake_minimum_required(VERSION 3.7)
project(pdndrv1 Fortran)
find_package(MPI REQUIRED)
find_package(arpack-ng 3.5 REQUIRED)
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)
add_executable(pdndrv1 pdndrv1.f)
target_link_libraries(pdndrv1 "${arpack_ng_LIBRARIES}" "${MPI_Fortran_LIBRARIES}" "${BLAS_LIBRARIES}" "${LAPACK_LIBRARIES}")
target_include_directories(pdndrv1 PUBLIC "${arpack_ng_INCLUDE_DIRS}" "${MPI_Fortran_INCLUDE_PATH}")
/tmp> export CMAKE_PREFIX_PATH=/path/to/arpack-ng/local # Should be done by module load.
/tmp> mkdir BUILD; cd BUILD; cmake ..; make
/tmp> …
=> CMake: find_package for both parpack and arpack (for now, works only for arpack).

CHANGES, PARPACK/SRC/MPI/Makefile.am, PARPACK/SRC/MPI/pcnaitr.f, PARPACK/SRC/MPI/pcnapps.f, PARPACK/SRC/MPI/pcnaup2.f, PARPACK/SRC/MPI/pcnaupd.f, PARPACK/SRC/MPI/pcneupd.f, PARPACK/SRC/MPI/pslamch10.f, PARPACK/SRC/MPI/psnaitr.f, PARPACK/SRC/MPI/psnapps.f, PARPACK/SRC/MPI/psnaup2.f, PARPACK/SRC/MPI/psnaupd.f, PARPACK/SRC/MPI/psneupd.f, PARPACK/SRC/MPI/pssaitr.f, PARPACK/SRC/MPI/pssapps.f, PARPACK/SRC/MPI/pssaup2.f, PARPACK/SRC/MPI/pssaupd.f, PARPACK/SRC/MPI/psseupd.f
fixes https://github.com/opencollab/arpack-ng/issues/50
=> rename pslamch to pslamch10 to avoid symbol collision with Scalapack

TESTS/icb_arpack_c.c, TESTS/icb_arpack_cpp.cpp, arpack.h, arpack.hpp
Fortran's logical type has size of 4 bytes, while C and C++ have `sizeof(bool)==1`. Thus it's no good to pass `bool[ncv]` array to a function expecting `logical(ncv)`.
Currently attempt to do this results in successful compilation and subsequent buffer overflow in e.g. `dseupd_c`. This is actually caught at run time by gcc>=5 by its stack smashing detector, leading to test failures.
This patch replaces `bool*` types expected by C and C++ bindings with `int*`, and corresponding declarations of the arrays in callers in the tests from `bool[3*ncv]` to `int[ncv]`.
=> Fix C and C++ bindings ABI

CHANGES, CMakeLists.txt, SRC/cgetv0.f, SRC/dgetv0.f, SRC/sgetv0.f, SRC/zgetv0.f, TESTS/Makefile.am, TESTS/bug_1315_double.c, TESTS/bug_1315_single.c, TESTS/bug_79_double_complex.f
Pull request for issue (#79) (force the initial residual to be in the range of the operator).
=> Force the residual vector to be in the range of OP. (#79)

.travis.yml
kill useless dep (added when confused by cmake problem related to iso_c_binding)
=> TravisCI: kill libc++-dev.

CMakeLists.txt
.. is OK only when the BUILD dir in under the root dir.
=> [BUG FIX] CMake: use ${PROJECT_SOURCE_DIR}.

.gitignore, .travis.yml, CHANGES, PARPACK/TESTS/MPI/Makefile.am, TODO, configure.ac
note: ax_mpi must be ran twice (first run in --enable-mpi scope
is lost when entering --enable-icb scope).
=> parpack: running autotools tests.

PARPACK/TESTS/MPI/Makefile.am, TODO
Not 100% sure... But according to this : https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html, it should be the way to handle mpirun with autotools. Check tests logs.
=> autotools: run parpack tests with "mpirun -n 2".

CMakeLists.txt
find_package files (*.cmake) stand for pkg-config files (*.pc).
pc files are supposed to be installed in local/lib/pkgconfig.
cmake files are supposed to be installed in local/lib/cmake.
=> CMake: cmake files install.

.travis.yml, CMakeLists.txt
Took 10 minutes to make things more like the "cmake way" : get all tests OK with "make test".
So you may drop "make check" (which is more the autotools way) as it's integrated in "make test".
Not sure you want that... If not, kill it !
=> CMake: merge "make test" and "make check"

PARPACK/TESTS/MPI/icb_parpack_cpp.cpp
@sylvestre this is a minor bugfix which, however, breaks compilation.
=> add missing header

.travis.yml, CMakeLists.txt, configure.ac
Hard-coded gnu++11 may break on specific archis (armel, ppc64el, ...).
=> C++11 (for ICB): do NOT use hard-coded gnu++11.

CHANGES, CMakeLists.txt, configure.ac
I usually add messages of that kind for all packages I handle: I do believe it makes things clear (trust what you got) and enable to avoid/detect problems (like the ones you have currently on armel, ppc64el, ...)
You may not want that...
=> Add configuration summary.

PARPACK/TESTS/MPI/icb_parpack_c.c, PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, TESTS/icb_arpack_c.c, TESTS/icb_arpack_cpp.cpp
Cosmetic bug ("better" way to get same thing - without this, sigma which
is used as an input, is implicitely converted from real to complex. Same
thing for the callee, but more "logical" for the caller).
=> [BUG FIX] When using *zneupd, sigma is complex.

PARPACK/TESTS/MPI/issue46.f
Cosmetic bug ("safer" way to get same thing).
=> [BUG FIX] howmny is defined as character*1 in pdseupd subroutine.

CMakeLists.txt, EXAMPLES/MATRIX_MARKET/arpackmm.cpp, EXAMPLES/MATRIX_MARKET/arpackmm.sh, configure.ac
arpackmm: enhancement
add control on pivot threshold if direct solver is used.
=> arpackmm: add --slvDrtPvtThd option.

configure.ac
=> Add error message if eigen is not found at configure time (autotools).

.travis.yml
Missing `-` in `-enable-icb-exmm`: switch replaced with `--enable-icb`.
fixing ILP64 CI !...
=> CI: make docker-run builds aware of PR commits.

.travis.yml
Try fix for broken ILP64 update.
=> TravisCI: fix ILP64 job. No need for security.debian.org.

VISUAL_STUDIO/arpack-ng_exports.def
Fix for issue #227
After deleting line from with dlaqrb_ in VISUAL_STUDIO/arpack-ng_exports.def solution builds successfully on Windows using Microsoft Visual Studio Community 2017 (Version 15.9.17) with Intel Visual Fortran Compiler 19.0.0.117.
=> Removed unnecessary export

.travis.yml
(slightly) improve fedora test in travis
- `yum` is deprecated and an alias for `dnf`
- `update` is a deprecated alias to `upgrade`, so only use `upgrade`
- install all packages in one go is faster
- prefer fedoraproject registry, which is generally more up-to-date
I don't think any of the deprecated commands should be dropped any time soon, so nothing important.
=> Various minor improvements for fedora test

ICB/parpack.hpp
=> parpack.hpp: don't use complex.h C macros.

CHANGES, EXAMPLES/MATRIX_MARKET/arpackSolver.hpp, PARPACK/SRC/MPI/icbpcn.F90, PARPACK/SRC/MPI/icbpdn.F90, PARPACK/SRC/MPI/icbpds.F90, PARPACK/SRC/MPI/icbpsn.F90, PARPACK/SRC/MPI/icbpss.F90, PARPACK/SRC/MPI/icbpzn.F90, SRC/icbacn.F90, SRC/icbadn.F90, SRC/icbads.F90, SRC/icbasn.F90, SRC/icbass.F90, SRC/icbazn.F90
=> [BUG FIX - ICB] iparam/ipntr sizes may change depending on cases.

.gitignore, .travis.yml, CHANGES, CMakeLists.txt, ICB/debug_icb.F90, ICB/stat_icb.F90, PARPACK/SRC/MPI/icbpcn.F90, PARPACK/SRC/MPI/icbpdn.F90, PARPACK/SRC/MPI/icbpds.F90, PARPACK/SRC/MPI/icbpsn.F90, PARPACK/SRC/MPI/icbpss.F90, PARPACK/SRC/MPI/icbpzn.F90, PARPACK/TESTS/MPI/Makefile.am, PARPACK/TESTS/MPI/icb_parpack_c.c, PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, README.md, SRC/icbacn.F90, SRC/icbadn.F90, SRC/icbads.F90, SRC/icbasn.F90, SRC/icbass.F90, SRC/icbazn.F90, TESTS/icb_arpack_c.c, TESTS/icb_arpack_cpp.cpp, arpackdef.h.in, arpackicb.h.in, configure.ac
Just checking if this could be the casper bug from #246 ...
@turboencabulator  : do you see something wrong (pattern, misuse related to conditional, ...) in ` TESTS/Makefile.am ` ?
=> [BUG FIX] Architecture: arpackdef.h for C/C++, and, arpackicb.h for F77/F90.

.travis.yml, README.md
Fixing CI.
To test interface64, we need **I**LP64 blas/lapack : the only lib (I know available through CI) which provide them is intel-mkl. intel-mkl is available only in latest debian (but not in "old" ubuntu boxes last time I checked) : need docker+debian => apt-get update / upgrade may change packages !...
Don't remember why `apt-utils` was needed, but, if I added it at the time, there was a reason ! :D Hope it's not needed anymore (would make this a fix quick)
=> [CLEAN - TravisCI]: use bionic as it's now provided by TravisCI !

cmake/CoverallsGenerateGcov.cmake
With newer versions of cmake, an unquoted 6th argument gives the
following error:
STRING sub-command REGEX, mode REPLACE needs at least 6 arguments
total to command.
Quoting this fixes the issue.
fixing coverage : same problem than #278 in boost.
coverage is often wrong (results changing when commiting comments or CMake/autotools files !...) and not so stable : this could be the reason why... May get coverage more stable and even increase it.
=> [BUG FIX] coverage.

.travis.yml, CHANGES
=> TravisCI: add centos build.

CHANGES, ICB/arpack.hpp, PARPACK/SRC/MPI/icbpcn.F90, PARPACK/SRC/MPI/icbpdn.F90, PARPACK/SRC/MPI/icbpds.F90, PARPACK/SRC/MPI/icbpsn.F90, PARPACK/SRC/MPI/icbpss.F90, PARPACK/SRC/MPI/icbpzn.F90, SRC/icbacn.F90, SRC/icbadn.F90, SRC/icbads.F90, SRC/icbasn.F90, SRC/icbass.F90, SRC/icbazn.F90
Fix errors in order to use Arpack routines from C++ calls
- Fix typo in arpack.hpp. bmat for general matrix was "B" instead of "G"
- Fix in iso_c_binding (.F90 files) pass scalar arguments instead of array of chars which caused instant crashes
The above were tested in Windows using Microsoft Visual Studio 2017 & 2019 and Intel Fortran 2020 compiler.
=> Fix a typo in arpack.hpp + some issues in iso_c_binding

TESTS/bug_79_double_complex.f
In bug_79_double_complex, the bitwise comparison `res1 .ne. res2`
returns true on some archs (i586) though `res1` and `res2` are equal upto
double precision. Instead compare the absolute value of their difference
to double precision 0 which works on all archs. Fixes #269.
=> [BUG FIX] Compare difference to 0 for equality.

CHANGES, CMakeLists.txt
older compilers may not enable this by default.
- fix the comment in https://github.com/opencollab/arpack-ng/issues/297
- `add_library( ... INTERFACE ...)` is not supported in cmake 2
=> add C99 standard checking to `CMakeLists.txt` & minimum CMake version changed to CMake3

.github/workflows/jobs.yml
fixing issue : fix github actions ?
PR seems to take master as a reference (need `pull_request_target` to get docker secrets from master branch of the opencollab reference repo...) : PR seems to still run `docker_centos` (master) even if the PR branch renamed it (`docker_redhat`) ?!...
blind-pushing on master: no choice...
=> Replace centos with redhat.

CHANGES, PARPACK/SRC/BLACS/pcgetv0.f, PARPACK/SRC/BLACS/pcnaitr.f, PARPACK/SRC/BLACS/pcnaup2.f, PARPACK/SRC/BLACS/pcneupd.f, PARPACK/SRC/BLACS/pzgetv0.f, PARPACK/SRC/BLACS/pznaitr.f, PARPACK/SRC/BLACS/pznaup2.f, PARPACK/SRC/BLACS/pzneupd.f, PARPACK/SRC/MPI/pcgetv0.f, PARPACK/SRC/MPI/pcnaitr.f, PARPACK/SRC/MPI/pcnaup2.f, PARPACK/SRC/MPI/pcneupd.f, PARPACK/SRC/MPI/pzgetv0.f, PARPACK/SRC/MPI/pznaitr.f, PARPACK/SRC/MPI/pznaup2.f, PARPACK/SRC/MPI/pzneupd.f, SRC/Makefile.am, SRC/ccdotc.f, SRC/cgetv0.f, SRC/cnaitr.f, SRC/cnaup2.f, SRC/cneupd.f, SRC/zgetv0.f, SRC/znaitr.f, SRC/znaup2.f, SRC/zneupd.f, SRC/zzdotc.f
macOS portability
See also https://github.com/Reference-ScaLAPACK/scalapack/pull/51.
=> [c,z]dotc => [cc,zz]dotc

CHANGES, CMakeLists.txt
When OpenBLAS is the only BLAS/LAPACK that is installed on the build system, the static linker flags in the pkg-config files might be wrong.
They contain the following line:
```
Libs.private: BLAS::BLAS
```
It should be:
```
Libs.private: -lopenblas
```
During the configuration step, the following is printed:
```
-- BLAS:
-- link:    F:/msys64/ucrt64/lib/libopenblas.dll.a
-- LAPACK:
-- link:    BLAS::BLAS
```
That seems to be caused by the following command in the `CMakeLists.txt` file:
```
get_target_property(LAPACK_LIBRARIES LAPACK::LAPACK INTERFACE_LINK_LIBRARIES) # Get variables from target (*.pc/cmake, msg).
```
I'm not sure if this is a cmake bug or if this is the expected result.
Anyway, the value of `LAPACK_LIBRARIES` seems to be set correctly immediately before that command. …
=> cmake: Don't override BLAS/LAPACK linker flags.

CHANGES, TESTS/bug_58_double.f
The proposed solution relies on IEEE-754 standard definition of NaN,
https://stackoverflow.com/questions/17389958/is-there-a-standard-way-to-check-for-infinite-and-nan-in-fortran-90-95
This solves a problem that appears with `nvfortran` compiler using CMake build. By the way, why is the CMake build compiling the tests? If I am not wrong the `configure` build skips tests (compiles the libraries only).
=> Avoid isnan(), which is GNU-specific

.github/workflows/jobs.yml
Use action msys2/setup-msys2 to install the MSYS2 build environment.
Among other things, this caches the downloaded packages which might speed up the installation process. But the main advantage is imho that it simplifies the commands that are used for building, and makes them easier to read.
=> Simplify build rules for CI on Windows

SRC/dnapps.f, SRC/dnaup2.f, SRC/dnaupd.f, SRC/dneupd.f, SRC/dsaup2.f, SRC/dsaupd.f, SRC/dstqrb.f, SRC/snapps.f, SRC/snaup2.f, SRC/snaupd.f, SRC/sneupd.f, SRC/ssaup2.f, SRC/ssaupd.f, SRC/sstqrb.f
Found via `codespell -q 3 -L canot,coo,inout,reord,workd`
=> Fix typos in SRC/

CMakeLists.txt
Tests were built by default with CMake, it is now an option set to ON by default to preserve previous behavior.
=> Make building tests an option in CMake

CMakeLists.txt
This PR swaps the order of linking to have LAPACK before BLAS.
Why ? When experimenting packaging the repo through vcpkg, I faced a peculiar problem when using static libraries (through WSL on Ubuntu 20.04 with GCC 9.4).
The first generated build command failed (with undefined references)
```bash
[1/2] /usr/bin/c++  -isystem /home/fabien/vcpkg/installed/x64-linux/include/arpack-ng -O2 -g -DNDEBUG -std=gnu++17 -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../../../main.cpp
[2/2] : && /usr/bin/c++ -O2 -g -DNDEBUG  CMakeFiles/main.dir/main.cpp.o -o main  /home/fabien/vcpkg/installed/x64-linux/lib/libarpack.a  /home/fabien/vcpkg/installed/x64-linux/lib/libopenblas.a  /home/fabien/vcpkg/installed/x64-linux/lib/liblapack.a  -lm …
```
=> Link to LAPACK before BLAS

.github/workflows/jobs.yml, CHANGES, CMakeLists.txt
Binaries of examples were not able to find `libarpack.dll` and failing, while tests were passing. The main difference in CMakeLists was setting the working directory for examples and not for tests. The binaries are probably linked without an absolute path for the library and searching the DLL in local folder. Changing the working directory in CMake changed the search local path where the DLL is absent.
To fix using MPI examples on Windows, the following was necessary:
* Add flag `-fallow-invalid-boz` fixing false positive errors on comments, e.g.
* >    87 | c  1. D.C. Sorensen, "Implicit Application of Polynomial Filters in
Warning: missing terminating " character 
* Replace `mpirun` by standard `mpiexec`
* Fix working directory of tests for MPI binaries
=> Run all examples for job `windows_latest_cmake` in CI

CHANGES, CMakeLists.txt, Makefile.am, pkg-config/arpack.pc.in, pkg-config/arpackSolver.pc.in, pkg-config/parpack.pc.in
=> [BUG FIX] Fix install: headers in /path/to/local/include/arpack

CHANGES, README.md
https://github.com/opencollab/arpack-ng/issues/401#issuecomment-1454895226 
> The original ARPACK site [rice.edu] is no longer accessible, unfortunately.
> The ARPACK manual (e.g. [here](http://li.mit.edu/Archive/Activities/Archive/CourseWork/Ju_Li/MITCourses/18.335/Doc/ARPACK/Lehoucq97.pdf)),
@sylvestre: do you prefer to git-add the pdf in the repo? In case the links gets unavailable in the future (like rice.edu is now - seems impossible from now to get original ARPACK / PARPACK tarballs)?
=> README: document where to find arpack user's guide.

CHANGES, README.md
Close https://github.com/opencollab/arpack-ng/issues/394#issuecomment-1426761739
Update readme to describe a bit more the possibility to install it on Windows. (Better late than never)
=> Add details on Windows installation

CHANGES, arpackdef.h.in
fixing issues in icb header.
- I macro is defined by complex.h on windows which is also defined in arpackSolver. IMO, this macro is useless, so it is undef.
- Distinct icx from cl on windows because icx uses clang-cl which defined _MSC_VER as well.
=> Fix windows icb macros

CMakeLists.txt
fixing issue46_tst run failure on certain systems
See https://github.com/opencollab/arpack-ng/issues/417
-
-
-
=> Update CMakeLists.txt , add mpiexec to issue46_tst run

README.md
Fixing package name typos in the README, where the package search via CMakes `find_package()` is demonstrated.
Use `arpackng` as package name instead of `arpack-ng`, as CMake won't find the installed Arpack-library with the latter.
=> Fix package name in CMake find_package() examples

README.md
cmake option for mkl BLA_VENDOR=INTEL works for obsolete verdions, replaced with INTEL10_64lp and INTEL10_64ilp for lp64 and ilp64 respectively, as reported here: https://cmake.org/cmake/help/latest/module/FindBLAS.html
=> Update README.md MKL options

CMakeLists.txt
To stop on first error, the cmake test should be called either as `COMMAND ${BASH_PROGRAM} -eu arpackmm.sh` or `COMMAND arpackmm.sh`. Calling bash onto the script file in ctest skips the shebang line of the script (which contains `#!/bin/bash -eu`). See #433 for the proof.
I used the former explicit version to avoid problem if the file is not executable
=> Fix error report in ctest when calling bash script

CHANGES, EXAMPLES/PYARPACK/pyarpackDenseLDLT.py.in, EXAMPLES/PYARPACK/pyarpackDenseLUPP.py.in, EXAMPLES/PYARPACK/pyarpackSparseCGILU.py.in, EXAMPLES/PYARPACK/pyarpackSparseLDLT.py.in, EXAMPLES/PYARPACK/pyarpackSparseLU.py.in
My proposal for fixing #432 
* Swapping matrices `pyarpackSparseLDLT` &lrarr; `pyarpackSparseLU`
* Swapping matrices `pyarpackDenseLDLT` &lrarr; `pyarpackDenseLUPP`
* `pyarpackCGILU` solves for hermitian matrices (and only non-general due to risk of losing positive definitness with shift-inverse)
=> Update pyarpack tests with SPD solvers

configure.ac
The second argument to `AC_SUBST` is placed on the right-hand-side of a shell variable assignment.  Without the single quotes, `${libdir}` is expanded when that variable assignment is executed, which is earlier than we want.
Discovered while testing #183, when `pkg.m4` is missing or too old.
=> Quote the default pkgconfigdir

CHANGES, PARPACK/SRC/MPI/Makefile.am
Alternate solution to #448.  See discussion on #449.
@loqs Try this, I think all FFLAGS will be present.
=> Build all PARPACK files with optimization

CHANGES, README.md
=> Add documentation on ILP64.

.github/workflows/emulated.yml
Use a GitHub action to install Alpine Linux for different, less common architectures that are emulated with qemu (apart from x86).
Additionally, Alpine Linux is one of those distributions that are based on musl (instead of glibc).
This increases coverage for different configurations in CI.
This PR adds GitHub action runners that build on Alpine Linux. It uses an action from the GitHub marketplace to install the required packages and set up `qemu` for subsequent steps (if necessary to emulate the respective architecture).
The emulated hardware can be slow. Especially compiling C++ objects seems to take quite some time. In preliminary tests, building ARPACK in the given configuration on emulated hardware took about 30 minutes.
This PR uses `ccache` to try to mitigate that. In preliminary …
=> Add CI runners on emulated hardware

.github/workflows/jobs.yml
Avoid version conflict with numpy on macOS runners.
Binary packages from different distributors could be built with different versions of dependencies. If these different versions are using an incompatible API or ABI this could lead to errors on build or execution time.
Try to install as many packages as possible from the same distributor (Homebrew in this case). I.e., no longer install numpy from pip while Python is installed from Homebrew.
This also simplifies the build rules for that job a bit. No virtual Python environment is needed.
Also, use non-conflicting configuration settings when it comes to the BLAS and LAPACK implementations on the macOS runners.
=> CI: Install numpy from Homebrew on macOS

.github/workflows/jobs.yml
Add CI for CLANG64 environment of MSYS2.
Add runners for different configurations (MPI, INTERFACE64) on MinGW-w64.
This picks up on #415.
The [CLANG64 environment](https://www.msys2.org/docs/environments/) of MSYS2 uses a toolchain that it almost entirely based on LLVM tools. That includes compilers (incl. LLVM Flang), linker, and LLVM libc++ (instead of GNU's libstdc++). Most common build environments are based on GNU tools (apart from maybe macOS and MSVC on Windows).
It might be worth testing unusual build environments in CI to make sure they don't break unintentionally.
This PR adds runners for that build environment.
It also adds Eigen3 as an additional build dependency on MinGW to test it on that platform.
Additionally, it adds runners for the following configurations (to the UCRT64 …
=> CI: Add CI for CLANG64 environment of MSYS2

CHANGES, PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, TESTS/icb_arpack_cpp.cpp
Fix compiler errors with some version of libstdc++ (maybe other C++ standard libraries are also affected).
```c++
/home/abuild/rpmbuild/BUILD/arpack-ng-3.9.1/TESTS/icb_arpack_cpp.cpp:68:16: error: no member named 'domain_error' in namespace 'std'
68 |     throw std::domain_error("Error inside ARPACK routines");
|           ~~~~~^
/home/abuild/rpmbuild/BUILD/arpack-ng-3.9.1/TESTS/icb_arpack_cpp.cpp:76:28: error: no member named 'runtime_error' in namespace 'std'
76 |   if (info < 0) throw std::runtime_error("Error in seupd, info " + std::to_string(info));
|                       ~~~~~^
/home/abuild/rpmbuild/BUILD/arpack-ng-3.9.1/TESTS/icb_arpack_cpp.cpp:85:37: error: no member named 'domain_error' in namespace 'std'
85 |     if (eps > tol_check) throw std::domain_error("Correct eigenvalues …
```
=> Add missing stdexcept header

.github/workflows/jobs.yml, CHANGES, CMakeLists.txt
Change configuration of some ctests on Windows so they work "out of the box".
Windows doesn't have a mechanism similar to rpaths. Instead, shared libraries are searched in the current working directory and in the directory with the executable followed by directories in the environment variable PATH.
Add the path to the shared libarpack library to PATH for ctests that run executables that are located in a different directory and that set the current working directory not to the directory with the libarpack.dll. Use a generator expression that should be working independent on the CMake generator.
Also remove the previously added work-around from the CI rules for MinGW that is no longer needed with that change.
=> Make ctests platform independent
