VISUAL_STUDIO/arpack-ng.vfproj
Added two missing files to the visual studio project, and set the paths
to be consistent.
=> Address Visual Studio build for Issue #8.

.travis.yml
=> Use the new travis infrastructure

.travis.yml, CMakeLists.txt, README
I included a CMakeLists.txt file (adopted from https://github.com/feymark/arpack.git) to support cmake out of code builds.
=> cmake support

PARPACK/SRC/MPI/pdlamch10.f
fixes https://github.com/opencollab/arpack-ng/issues/34
in reference to this PR https://github.com/opencollab/arpack-ng/pull/21
=> fix pdlamch10 return variable

CHANGES, CMakeLists.txt, README
fixes https://github.com/opencollab/arpack-ng/issues/38
tested on macOS.
@m-reuter @nalimilan: you might want to give a quick look at these Cmake-related changes.
=> Improve cmake build

CMakeLists.txt
& set default build type to release
=> Disable C++ compiler detection

CHANGES, CMakeLists.txt, SRC/dneupd.f, SRC/sneupd.f, TESTS/Makefile.am, TESTS/bug_58_double.f
I added a test is TESTS/bug_58_double.f
=> Test for issue #58

SRC/dneigh.f, SRC/sneigh.f
DLAHQR and SLAHQR should be LAPACK routine
The comment is fixed in dneigh.f and sneigh.f
=> fix {d|s}lahqr comment, which should be LAPACK routine

.travis.yml, CMakeLists.txt
Fix issue #64.
Cmake provided check but no test. Add a test target.
=> Run the testsuite in the CI with cmake #64.

CHANGES, CMakeLists.txt
Provide tarball generation using cmake (cpack). May be convenient to distribute tarballs.
=> Provide tarball generation using cmake (cpack).

PARPACK/SRC/BLACS/pdnaitr.f, PARPACK/SRC/BLACS/pdnapps.f, PARPACK/SRC/BLACS/pdsaitr.f, PARPACK/SRC/BLACS/psnaitr.f, PARPACK/SRC/BLACS/psnapps.f, PARPACK/SRC/BLACS/pssaitr.f, PARPACK/SRC/MPI/pdnaitr.f, PARPACK/SRC/MPI/pdnapps.f, PARPACK/SRC/MPI/pdsaitr.f, PARPACK/SRC/MPI/psnaitr.f, PARPACK/SRC/MPI/psnapps.f, PARPACK/SRC/MPI/pssaitr.f, SRC/dnaitr.f, SRC/dnapps.f, SRC/dsaitr.f, SRC/snaitr.f, SRC/snapps.f, SRC/ssaitr.f
Found them in a downstream project and decided to submit fixes upstream.
=> Fixed some trivial comment code typos

CMakeLists.txt
I believe these extra useless lines come from a bad merge.
Franck
=> [CLEAN] CMake: kill useless lines (coming from bad merge ?).

TESTS/icb_arpack_cpp.cpp, arpack.hpp
note: as const is added on function arguments, this should be safe from C <-> C++ pitfalls.
=> arpack.hpp: add const to improve C++ integration.

.travis.yml, CHANGES, CMakeLists.txt, Makefile.am, PARPACK/EXAMPLES/MPI/README.CALLING-PARPACK-FROM-C-OR-CPP, PARPACK/SRC/MPI/Makefile.am, PARPACK/SRC/MPI/icbpcn.f90, PARPACK/SRC/MPI/icbpdn.f90, PARPACK/SRC/MPI/icbpds.f90, PARPACK/SRC/MPI/icbpsn.f90, PARPACK/SRC/MPI/icbpss.f90, PARPACK/SRC/MPI/icbpzn.f90, PARPACK/TESTS/MPI/Makefile.am, PARPACK/TESTS/MPI/icb_parpack_c.c, PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, TODO, configure.ac, parpack.h, parpack.hpp
The code and cmake tests work on debian/testing.
There is a cmake specific problem on travis/ubuntu : travis fails (icb_parpack_cpp link KO) => if somebody can help here...
Not a autotools guru : autotools tests do not compile / run => if somebody can help here...
If somebody can help : would be good, feel free to commit at my side (https://github.com/fghoussen/arpack-ng/commits/icb_parpack)... And otherwise no such a big deal : forget the PR and close this.
Franck
=> parpack : add iso_c_binding support.

README.md, cmake/CoverallsGenerateGcov.cmake
=> Misc. typos

CHANGES, CMakeLists.txt, Makefile.am, PARPACK/SRC/MPI/Makefile.am, PARPACK/TESTS/MPI/icb_parpack_c.c, PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, SRC/Makefile.am, TESTS/icb_arpack_c.c, TESTS/icb_arpack_cpp.cpp, configure.ac, debug.h, debug_c.h, debug_c.hpp, debug_icb.f90, debug_init.f90
=> iso_c_binding: add debug support.

CHANGES, CMakeLists.txt, Makefile.am, PARPACK/SRC/MPI/Makefile.am, PARPACK/TESTS/MPI/icb_parpack_c.c, PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, README.md, SRC/Makefile.am, TESTS/icb_arpack_c.c, TESTS/icb_arpack_cpp.cpp, configure.ac, stat.h, stat_c.h, stat_c.hpp, stat_icb.f90
Should be the last PR !... :D Hope coverage will not break
=> iso_c_binding: add statistics support.

CMakeLists.txt, TESTS/icb_arpack_cpp.cpp, arpack.hpp, configure.ac
Use GNU extensions otherwise _Complex_I is not valid.
=> Add C++11 interface

TESTS/icb_arpack_cpp.cpp, arpack.hpp
Per review.  Formatting changes to match Google format.
=> Remove appended _c and update comments

CMakeLists.txt
Seen it yesterday, but, no time for it !
=> [BUG FIX] Missing include.

.travis.yml
=> Travis-CI: use jobs (easier to check out what's wrong).

.travis.yml
if error occured (cmake bug, autotools OK, increase tail).
=> [BUG FIX] TravisCI: show build error or test log to know what is wrong

.travis.yml
This was need to PR as the ilp64 branch didn't exist on opencollab/master.
-
-
-
=> [BUG FIX] changes needed after PR#165 (ILP64).

EXAMPLES/MATRIX_MARKET/arpackmm.cpp
=> arpackmm: add check.

.travis.yml
=> Add back the coveralls push

CMakeLists.txt, EXAMPLES/MATRIX_MARKET/arpackmm.cpp, EXAMPLES/MATRIX_MARKET/arpackmm.sh, configure.ac
Reverts opencollab/arpack-ng#178
=> Revert "arpackmm: add --slvDrtPvtThd option."

EXAMPLES/MATRIX_MARKET/arpackmm.cpp, EXAMPLES/MATRIX_MARKET/arpackmm.sh
arpackmm: enhancement.
Enable to compute ritz or schur vectors.
=> Arpackmm: add --schur option.

CMakeLists.txt
=> Add parpack files in the coveralls report.

CHANGES, EXAMPLES/MATRIX_MARKET/arpackmm.cpp, EXAMPLES/MATRIX_MARKET/arpackmm.sh
arpackmm: enhancement
add control on preconditioners if iterative solvers are needed.
=> arpackmm: add --slvItrPC option (PC: Jacobi, ILU).

CHANGES, EXAMPLES/MATRIX_MARKET/arpackmm.cpp, EXAMPLES/MATRIX_MARKET/arpackmm.sh
arpackmm: enhancement.
enable use of [sc]*upd.
=> Arpackmm: add --simplePrec option (to enable use of [sc]*upd).

EXAMPLES/MATRIX_MARKET/README, EXAMPLES/MATRIX_MARKET/arpackmm.cpp, EXAMPLES/MATRIX_MARKET/arpackmm.sh
arpackmm: refactorisation.
- refactorisation
- documentation, help
=> arpackmm: refactorisation, documentation, help, add timers.

.travis.yml, EXAMPLES/MATRIX_MARKET/README, EXAMPLES/MATRIX_MARKET/arpackmm.sh
fixing issue #192 ?
reduce message in logs to avoid breaking CI (redirect message in file)
=> CI: reduce logs, fix precision problem, increase coverage.

.travis.yml, CMakeLists.txt
CMake: make build dir look like source dir.
=> CMake: make build dir look like source dir.

PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, TESTS/icb_arpack_cpp.cpp
fixing issue #195 ?
- [BUG FIX] arpack may succeed to compute more EV than expected.
=> [BUG FIX] arpack may succeed to compute more EV than expected.

CMakeLists.txt, EXAMPLES/MATRIX_MARKET/Makefile.am
arpackmm: run test script with bash.
this is related to #204
=> arpackmm: run test script with bash.

.travis.yml, CHANGES, configure.ac
CI: Add ubuntu:bionic using docker.
=> CI: Add ubuntu:bionic using docker.

CHANGES, PARPACK/TESTS/MPI/icb_parpack_cpp.cpp, TESTS/icb_arpack_cpp.cpp
fixing issue #195 ?
[BUG FIX] fix check precision which may fail with some ATLAS versions.
=> [BUG FIX] fix check precision which may fail with some ATLAS versions.

CHANGES
Update changelog for #210/#211
I hope I've done this correctly. LMK if not and how/where you want me to document the minor change in #211.
=> Update CHANGES for #210/#211

CHANGES, arpack-ng-config.cmake.in, arpack.pc.in
fixing issue #214 (at least partially).
=> [BUG FIX] fix cmake/pc files: enable linking from outside.

.travis.yml, CMakeLists.txt, configure.ac
Add cmake/autotool variables in autotool/cmake to generate pc/cmake files.
bug fix
=> [BUG FIX] Install: generating crossed cmake/pc files.

EXAMPLES/MATRIX_MARKET/arpackSolver.hpp, EXAMPLES/MATRIX_MARKET/arpackmm.cpp
arpackSolver: cleaning, refactoring.
=> arpackSolver: cleaning, refactoring.

.travis.yml, ICB/parpack.hpp, configure.ac
fixing issue #233 ?...
@cesss : you tell me what to do next !... not mac-based
=> [TravisCI] Add osx job

EXAMPLES/PYARPACK/pyarpackDenseLDLT.py.in, EXAMPLES/PYARPACK/pyarpackDenseLLT.py.in, EXAMPLES/PYARPACK/pyarpackDenseLUPP.py.in, EXAMPLES/PYARPACK/pyarpackDenseLURR.py.in, EXAMPLES/PYARPACK/pyarpackDenseQRPP.py.in, EXAMPLES/PYARPACK/pyarpackDenseQRRR.py.in, EXAMPLES/PYARPACK/pyarpackRestart.py.in, EXAMPLES/PYARPACK/pyarpackSparseBiCGDiag.py.in, EXAMPLES/PYARPACK/pyarpackSparseBiCGILU.py.in, EXAMPLES/PYARPACK/pyarpackSparseCGDiag.py.in, EXAMPLES/PYARPACK/pyarpackSparseCGILU.py.in, EXAMPLES/PYARPACK/pyarpackSparseLDLT.py.in, EXAMPLES/PYARPACK/pyarpackSparseLLT.py.in, EXAMPLES/PYARPACK/pyarpackSparseLU.py.in, EXAMPLES/PYARPACK/pyarpackSparseQR.py.in
clean if you don't want python2
=> [CLEAN] pyarpack: does not python2.

configure.ac
fixing issue #252 ? Seems OK on debian
=> [BUG FIX] configure must be Bourne shell compatible.

CMakeLists.txt, EXAMPLES/PYARPACK/README, EXAMPLES/PYARPACK/pyarpack.cpp
=> pyarpack: improve documentation.

.travis.yml, CMakeLists.txt, README.md, configure.ac
Switch eigen version to latest one : https://github.com/opencollab/arpack-ng/pull/259#issuecomment-636797682. On top of #260 .
=> Eigen version

.travis.yml, scripts/travis_fedora.sh
- pull in less dependencies
- Show a nicer name
=> Fedora travis

.travis.yml, scripts/travis_ubuntu.sh
=> [TravisCI] Add linuxmint job. 

.travis.yml, scripts/travis_ubuntu.sh
=> [TravisCI] : add eoan / focal build.

.travis.yml
checking issue #273. @lteneyck : what's your xcode version ?
=> [TravisCI] Test osx formula.

.travis.yml, CHANGES
=> TravisCI: add opensuse build.

.travis.yml, CHANGES, README.md, TESTS/icb_arpack_cpp.cpp, configure.ac
Was told this is supposed to work ?!.... checking... Related to #6
=> [TravisCI] OS X: running the whole test suite.

CMakeLists.txt, README.md, arpack-ng-config.cmake.in
=> [CMake] Use targets following "modern CMake".

.travis.yml
=> [BUG FIX] TravisCI: openmpi not found on osx.

.travis.yml, CHANGES, scripts/travis_centos.sh
CI: add build for centos7
- See https://github.com/opencollab/arpack-ng/pull/299#issuecomment-801342448
=> CI: add support for centos:7

.github/workflows/jobs.yml
as discussed on #317 - PRs are not pushes, so it needs to be said explicitly.
See https://github.com/opencollab/arpack-ng/pull/317#issuecomment-932994090
=> allow triggering GitHub Actions for PRs

CHANGES, CMakeLists.txt, PARPACK/TESTS/MPI/icb_parpack_c.c, TESTS/Makefile.am, TESTS/bug_1315_double.c, TESTS/bug_1315_single.c, TESTS/icb_arpack_c.c, configure.ac
fixing several issues discovered when debugging
=> Ilp64 lesson learned

.github/workflows/jobs.yml
fixing issue : fix github actions ? PR does not checkout PR branch
=> Fix github actions: checkout branch we need to test (master or PR branch).

cmake/tstCMakeInstall.sh.in, pkg-config/tstAutotoolsInstall.sh.in
CMake may change install directory structure (local/lib or
local/lib/arch). Use find to prevent tests from this.
fixing CI.
=> [BUG FIX] Test install.

README.md
=> README.md: fix style.

CHANGES, CMakeLists.txt, cmake/tstCMakeInstall.sh.in
Fixing install. Related to #358.
=> Create one .cmake file per arpack-ng flavor (32-bits, 64-bits, ILP64).

EXAMPLES/PYARPACK/README, README.md
=> [DOC] Add notes in pyarpack documentation.

.github/workflows/jobs.yml, CHANGES, CMakeLists.txt, EXAMPLES/PYARPACK/README
[CI] Test python feature on macos.
Related to #289
=> [CI] Test python feature on macos.

CHANGES, EXAMPLES/MATRIX_MARKET/arpackSolver.hpp
arpackSolver: fixing error messages
=> arpackSolver: fix error messages.

README.md
=> How to use arpack-ng with Intel MKL.

.github/workflows/jobs.yml, EXAMPLES/PYARPACK/README, EXAMPLES/PYARPACK/pyarpack.cpp, EXAMPLES/PYARPACK/pyarpackDenseLDLT.py.in, EXAMPLES/PYARPACK/pyarpackDenseQRPP.py.in, EXAMPLES/PYARPACK/pyarpackDenseQRRR.py.in, EXAMPLES/PYARPACK/pyarpackSparseBiCGILU.py.in, EXAMPLES/PYARPACK/pyarpackSparseCGILU.py.in, EXAMPLES/PYARPACK/pyarpackSparseLDLT.py.in, EXAMPLES/PYARPACK/pyarpackSparseQR.py.in
Fix CI to finally be able to move on with other PRs. (Tested here https://github.com/FabienPean/arpack-ng/pull/3)
- Simplify and fix the CI for macOS with latest github actions runner images (issues with python
- Fix python examples by removing deleted numpy.complex type in v 1.24 (deprecated since 1.20) and use built-in complex
=> Fix CI macOS jobs

.github/workflows/jobs.yml
=> [CI] Run full test suite (including eigen tests).

CHANGES, README.md
=> Prepare new release

README.md
=> Add comments to README.

EXAMPLES/MATRIX_MARKET/arpackSolver.hpp, EXAMPLES/MATRIX_MARKET/arpackmm.cpp
=> arpackSolver: cut-off arpack workspace dim.

CHANGES, README.md
=> README: document how to use ICB.

CHANGES, EXAMPLES/MATRIX_MARKET/arpackmm.sh
=> Fix arpackmm test suite

.github/workflows/jobs.yml
=> [CI] Fix macos job.

EXAMPLES/MATRIX_MARKET/arpackSolver.hpp, EXAMPLES/MATRIX_MARKET/arpackmm.cpp
=> arpackmm: improve command line for testing.
